version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: balance_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: laravel
      POSTGRES_USER: sail
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: balance_app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./:/var/www/html
      - ./docker/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: sail
      DB_PASSWORD: secret

volumes:
  postgres_data:
